### ISSUE TITLE
issue of installtion

### ISSUE THREAD

**Issue by miki98703** [RCVolus/lol-pick-ban-ui#142]
in step 10, window powershell print out this phrases

./src/europe/style/index.module.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-7-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-7-4!./src/europe/style/index.module.scss)
Node Sass version 7.0.0 is incompatible with ^4.0.0 || ^5.0.0 || ^6.0.0.

I have to downgarde node in 4.00 or5.00 or 6.00?
(i don't know about computer programing, so please tell me more detailed)

**Comment by sdomi4** [comment]
This is a dependency issue, you can try manually downgrading to 6.0.0, or wait until we fix this so you can just run the tool :)

**Comment by miki98703** [comment]
Althougn I downgraded node to 6.0.0 and  opened  a powershell at layout-volu-europe and i follow the step 9 
but powershell print out this phrases


PS D:\User\Downloads\lol-pick-ban-ui-master (1)\lol-pick-ban-ui-master\layouts\layout-volu-europe> npm install
- @babel/core@7.16.0 node_modules\@babel\preset-env\node_modules\@babel\core
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\helper-compilation-targets\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\helper-compilation-targets\node_modules\@babel\core\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-async-generator-functions\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-async-generator-functions\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-dynamic-import\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-dynamic-import\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-export-namespace-from\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-export-namespace-from\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-json-strings\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-json-strings\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-logical-assignment-operators\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-logical-assignment-operators\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-object-rest-spread\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-object-rest-spread\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-optional-catch-binding\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-optional-catch-binding\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-private-methods\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-private-methods\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-unicode-property-regex\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-proposal-unicode-property-regex\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-async-generators\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-async-generators\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-class-properties\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-class-properties\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-dynamic-import\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-dynamic-import\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-export-namespace-from\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-export-namespace-from\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-json-strings\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-json-strings\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-logical-assignment-operators\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-logical-assignment-operators\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-object-rest-spread\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-object-rest-spread\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-optional-catch-binding\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-optional-catch-binding\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-top-level-await\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-syntax-top-level-await\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-arrow-functions\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-arrow-functions\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-async-to-generator\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-async-to-generator\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-block-scoped-functions\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-block-scoped-functions\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-block-scoping\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-block-scoping\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-classes\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-classes\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-computed-properties\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-computed-properties\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-destructuring\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-destructuring\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-dotall-regex\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-dotall-regex\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-duplicate-keys\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-duplicate-keys\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-exponentiation-operator\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-exponentiation-operator\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-for-of\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-for-of\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-function-name\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-function-name\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-literals\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-literals\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-member-expression-literals\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-member-expression-literals\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-modules-amd\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-modules-amd\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-modules-commonjs\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-modules-commonjs\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-modules-systemjs\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-modules-systemjs\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-modules-umd\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-modules-umd\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-named-capturing-groups-regex\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-named-capturing-groups-regex\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-new-target\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-new-target\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-object-super\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-object-super\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-parameters\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-parameters\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-property-literals\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-property-literals\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-regenerator\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-regenerator\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-reserved-words\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-reserved-words\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-shorthand-properties\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-shorthand-properties\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-spread\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-spread\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-sticky-regex\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-sticky-regex\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-template-literals\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-template-literals\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-typeof-symbol\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-typeof-symbol\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-unicode-escapes\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-unicode-escapes\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-unicode-regex\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\plugin-transform-unicode-regex\node_modules\semver
- @babel/core@7.12.3 node_modules\@babel\preset-env\node_modules\@babel\preset-modules\node_modules\@babel\core
- semver@5.7.1 node_modules\@babel\preset-env\node_modules\@babel\preset-modules\node_modules\semver
- source-map@0.5.7 node_modules\@babel\preset-env\node_modules\source-map
- jest-resolve@26.6.0 node_modules\jest-pnp-resolver\node_modules\jest-resolve
npm WARN optional Skipping failed optional dependency /react-scripts/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@2.3.2
npm WARN optional Skipping failed optional dependency /jest-haste-map/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@2.3.2
npm WARN optional Skipping failed optional dependency /watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@2.3.2
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.13
npm WARN @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.16.0 requires a peer of @babel/core@^7.13.0 but none was installed.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of type-fest@^0.13.1 but none was installed.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-hot-middleware@2.x but none was installed.
npm WARN @pmmmwh/react-refresh-webpack-plugin@0.4.3 requires a peer of webpack-plugin-serve@0.x || 1.x but none was installed.
npm WARN jest-config@26.6.3 requires a peer of ts-node@>=9.0.0 but none was installed.
npm WARN jsdom@16.7.0 requires a peer of canvas@^2.5.0 but none was installed.
npm WARN ws@7.5.5 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.5.5 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm WARN react-scripts@4.0.3 requires a peer of typescript@^3.2.1 || ^4 but none was installed.
npm WARN sass-loader@10.2.0 requires a peer of fibers@>= 3.1.0 but none was installed.
npm WARN sass-loader@10.2.0 requires a peer of node-sass@^4.0.0 || ^5.0.0 || ^6.0.0 but none was installed.
npm WARN sass-loader@10.2.0 requires a peer of sass@^1.3.0 but none was installed.
npm WARN terser@5.10.0 requires a peer of acorn@^8.5.0 but none was installed.
npm WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none was installed.
PS D:\User\Downloads\lol-pick-ban-ui-master (1)\lol-pick-ban-ui-master\layouts\layout-volu-europe> npm start

> layout-volu-europe@0.1.0 start D:\User\Downloads\lol-pick-ban-ui-master (1)\lol-pick-ban-ui-master\layouts\layout-volu-europe
> react-scripts start

D:\User\Downloads\lol-pick-ban-ui-master (1)\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\react-dev-utils\node_modules\globby\index.js:49
                ...taskOptions
                ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\User\Downloads\lol-pick-ban-ui-master (1)\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\react-dev-utils\globby.js:10:14)
    at Module._compile (module.js:541:32)

npm ERR! Windows_NT 10.0.19044
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! layout-volu-europe@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the layout-volu-europe@0.1.0 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the layout-volu-europe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs layout-volu-europe
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls layout-volu-europe
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\User\Downloads\lol-pick-ban-ui-master (1)\lol-pick-ban-ui-master\layouts\layout-volu-europe\npm-debug.log
PS D:\User\Downloads\lol-pick-ban-ui-master (1)\lol-pick-ban-ui-master\layouts\layout-volu-europe>
