### ISSUE TITLE
it's not working

### ISSUE THREAD

**Issue by leanbinh** [RCVolus/lol-pick-ban-ui#21]
I did follow the correct order but the error message keeps coming up like: (node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 406)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 408)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 410)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 412)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 414)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 416)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 418)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 420)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 422)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 424)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 426)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 428)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 430)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 432)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 434)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 436)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 438)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 440)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 442)
(node:14580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\leanb\Desktop\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:14580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 444)
  I don't know what to do

**Comment by LarsBaertschi** [comment]
Hey, are you sure that you have the League Client open? Usually this message appears when a connection to the League Client cannot be made.

**Comment by leanbinh** [comment]
> Hey, are you sure that you have the League Client open? Usually this message appears when a connection to the League Client cannot be made.

![image](https://user-images.githubusercontent.com/67872108/86977268-74692080-c1a6-11ea-8d30-079d6d46de9e.png)

I have completed all the steps, connected to lcu, but when connecting to localhost: 8999, I received response Cannot GET /

**Comment by LarsBaertschi** [comment]
Hey, once you get to that point you're done with setting up the backend.

It is intended, that you receive this message when you open up the backend. You need to install a frontend to access it. The backend is not directly visible in the browser.

**Comment by leanbinh** [comment]
ok I just have one more problem, that is about the simple layout. It does not work and the 404 message (http: // localhost: 5000 / layouts / layout-simple /? backend = ws: // localhost: 8999). and localhost:5000 only shows layout, not UI ban picks
![image](https://user-images.githubusercontent.com/67872108/86999430-caf15180-c1dc-11ea-8f92-7208e3d925f8.png)

**Comment by LarsBaertschi** [comment]
You have run the serve command in the directory "layouts/layout-simple".

You need to run it in the project root, so in the top.folder of the project. There where you also started the backend.

**Comment by leanbinh** [comment]
Can you give me the path?
![image](https://user-images.githubusercontent.com/67872108/87000150-89fa3c80-c1de-11ea-879e-d5aa333b68bf.png)

**Comment by LarsBaertschi** [comment]
right in there. Just shift + rightclick, select open powershell / command line and issue ```serve```

**Comment by leanbinh** [comment]
![image](https://user-images.githubusercontent.com/67872108/87000600-aea2e400-c1df-11ea-9ea3-3ae4adbf4f42.png)
it's not working!!

**Comment by LarsBaertschi** [comment]
not in the "backend" folder, in the root folder. The top level folder.

**Comment by leanbinh** [comment]
![image](https://user-images.githubusercontent.com/67872108/87000814-1d803d00-c1e0-11ea-842c-ebfbbe2613e9.png)
it's "lol-pick-ban-ui-master"?

**Comment by LarsBaertschi** [comment]
yes, but you need to open up another CMD window

**Comment by leanbinh** [comment]
ohh it's working!!!!! Thanks you very much

**Comment by LarsBaertschi** [comment]
You're welcome :)

**Comment by leanbinh** [comment]
I use cmd as a shortcut to run with adminis rights to connect to the LCU, for garena-managed servers, applications that want to connect to the LCU must have admin rights

**Comment by LarsBaertschi** [comment]
good note! I'll add that one.tho the docs.
