### ISSUE TITLE
UnhanlededPrimiseRejectionWarning

### ISSUE THREAD

**Issue by MaximilianRu** [RCVolus/lol-pick-ban-ui#58]
![issue](https://user-images.githubusercontent.com/23660832/109423613-73f4f280-79e0-11eb-9830-ccd8b203e5c6.PNG)

Hey, 
I have the same problem as some others here, that the backend won't work with "npm start"
`(node:4476) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'port' of undefined
    at LeagueDataProviderService.getCurrentData (C:\Users\Pasca\Desktop\Stream\lol-pick-ban-ui-master\lol-pick-ban-ui-master\backend-build\data\league\LeagueDataProviderService.js:58:97)
    at TickManager.runLoop (C:\Users\Pasca\Desktop\Stream\lol-pick-ban-ui-master\lol-pick-ban-ui-master\backend-build\TickManager.js:18:61)
    at Timeout.timeout.setInterval [as _onTimeout] (C:\Users\Pasca\Desktop\Stream\lol-pick-ban-ui-master\lol-pick-ban-ui-master\backend-build\TickManager.js:15:47)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)`

I tried to start powershell as admin, but wouldn't help. 
Adding the league path won't help either

**Comment by MarkL4YG** [comment]
Please make sure your LoL-Client is actually running when starting the overlay services.
This issue normally appears when the client is offline while the LCU broker attempts to read the local connection information to it.

**Comment by MaximilianRu** [comment]
It was running, even tested it wit starting the lol client after the backend server or without. None of these tries did help.

**Comment by MaximilianRu** [comment]
Found out, that this was actually a problem with the windows installation. 
After a fresh reinstall the pick ban server just worked fine

**Comment by MaximilianRu** [comment]
Found out, that this was actually a problem with the windows installation.
After a fresh reinstall the pick ban server just worked fine
