### ISSUE TITLE
Hi i keep getting this error everytime I try to run "npm start" on the volu-eu layout :(

### ISSUE THREAD

**Issue by stXwinter** [RCVolus/lol-pick-ban-ui#69]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

at validateString (internal/validators.js:125:11)
at Object.join (path.js:427:7)
at noopServiceWorkerMiddleware (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
at Layer.handle [as handle_request] (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\layer.js:95:5)
at trim_prefix (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:317:13)
at C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:284:7
at Function.process_params (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:335:12)
at next (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:275:10)
at launchEditorMiddleware (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
at Layer.handle [as handle_request] (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\layer.js:95:5)
at trim_prefix (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:317:13)
at C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:284:7
at Function.process_params (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:335:12)
at next (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:275:10)
at handleWebpackInternalMiddleware (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
at Layer.handle [as handle_request] (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\layer.js:95:5)
![Screenshot 2021-03-25 222517](https://user-images.githubusercontent.com/44768100/112474269-7ff78880-8dc3-11eb-8401-0be832204bd2.png)
![Screenshot 2021-03-25 222811](https://user-images.githubusercontent.com/44768100/112474272-8128b580-8dc3-11eb-91c6-c51d9347f107.png)

**Comment by stXwinter** [comment]
bump

**Comment by jtsteis** [comment]
https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re/62287792#62287792

Found this as the issue
