### ISSUE TITLE
everytime i do NPM start on the volu-europe layout i get this error

### ISSUE THREAD

**Issue by stXwinter** [RCVolus/lol-pick-ban-ui#77]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at Object.join (node:path:397:7)
    at noopServiceWorkerMiddleware (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (C:\Users\avera\Desktop\lol-pick-ban-ui-master\layouts\layout-volu-europe\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
![Screenshot 2021-04-26 183006](https://user-images.githubusercontent.com/44768100/116052895-719bd580-a6bd-11eb-8cc9-ec78723023d8.png)
![m4nLhlfU](https://user-images.githubusercontent.com/44768100/116052979-88422c80-a6bd-11eb-91ba-a2fca6088d2d.png)

**Comment by justinang1** [comment]
Does the project still run correctly? When does this error message come up.

You also need to use the following url to connect the app to the backend service (otherwise nothing will load): http://localhost:3000/?backend=ws://localhost:8999. 

I can also help you more over discord if you'd like: https://discord.gg/gs4rS6dGcM

**Comment by jtsteis** [comment]
https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re/62287792#62287792

Found this as the issue
